#!/bin/bash

ln -sf $PWD/vimrc  $HOME/.vimrc
ls -l $HOME/.vimrc

ln -sf $PWD/bash.config  $HOME/.bash_aliases
ls -l $HOME/.bash_aliases

ln -sf $PWD/tmux.conf  $HOME/.tmux.conf
ls -l $HOME/.tmux.conf
